version: '3.8'
services:
  # db:
  #   image: postgres
  #   ports:
  #     -"80-8000"
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data 
  app:
    container_name: 'app_map'
    build: ./app
    ports: 
      - "5252:5252"
    network_mode: host
volumes:
  pgdata:
